[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'hewes/unite-gtags'
depends = 'unite.vim'

[[plugins]]
repo = 'rking/ag.vim'
