[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]] repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'surround.vim'

